### ISSUE TITLE
Not all item sets load in Champion folders with large numbers of item sets. 

### ISSUE THREAD

**Issue by jblanchard1** [Cadrach/lol_ise#9]
### Browser (Chrome, Safari, Internet Explorer) and Version
Google Chrome Version 55.0.2883.87 m

### Provide a Screenshot when possible
![untitled](https://cloud.githubusercontent.com/assets/17169702/21512333/387fba2c-cc7a-11e6-86f3-d52f9041f188.png)

### Steps to reproduce
Drag a "Champions" folder that is very large into the editor. Example of large folder: 
[Champions.zip](https://github.com/Cadrach/lol_ise/files/674918/Champions.zip)

Only item sets up to a certain point will load. (In the most recent case, it loaded up to Swain, but no further.)

**Comment by Cadrach** [comment]
I have increased the maximum number of loaded file 3000 (from 2000) this should solve this issue.

**Comment by jblanchard1** [comment]
The problem seems to be continuing. I have changed my champions folder a bit (
[Champions.zip](https://github.com/Cadrach/lol_ise/files/681753/Champions.zip)) but the entire thing is still not loading. It continues down to Taric now, probably because I removed some duplicates so there are fewer files, but it is still not completely loading. 

It appears to be on version 0.5, since the 0.5 is in the top left corner and has the changelog if I click on it.
